### ISSUE TITLE
We need more tests

### ISSUE THREAD

**Issue by crichID** [githubschool/our-book-app#3]
**tl;dr** I think our test coverage is a  little light. Maybe we can add a few more.

### Background

_Cross link to previous conversations about this topic or relevant code_

### Discussion

_What should we do and why should we do it?_

### Next Steps

- [ ] Add some tests
- [ ] Make  sure they pass

### Mentions

@beardofedu

**Comment by beardofedu** [comment]
I love this idea!!!!
